#include <stdio.h>
#include <xc.h>
#include "CONFI.h"

#define _XTAL_FREQ 4000000
#define MCT PORTAbits.RA4
#define MCT PORTAbits.RA5
#define MCT PORTAbits.RA6
#define PP_PA PORTBbits.RB3

// DOS PINES PARA LAS FUNCIONES GIRAR IZQUIERDA 10, GIRAR DERECHA01, DESCENDER 00, ASCENDER 11 BRAZO NEUMATICO
// DOS PINES PARA LAS FUNCIONES GIRAR IZQUIERDA 10, GIRAR DERECHA01, DESACTIVAR (VENTOSA) 00, ACTIVAR (VENTOSA) 11 MANIPULADOR
// UN PIN PARA LOS SENSORES FINAL DE CARRERA DERECHA,FINAL DE CARRERA IZQUIERDA
void main(void) 
{
    ADCON1bits.PCFG = 0x0F;
    TRISA = 0x00;
    
}